### PR TITLE
Temporary fix for Area 4 Gamma Error

### LINKED ISSUE #209: Memory errors for Area 4 metroid
Do this with the other spawngroups: https://github.com/randovania/open-samus-returns-rando/blob/5cbc2e5263abfa42ff7d1b21db6346c14d501035/src/open_samus_returns_rando/files/levels/s040_area4.lua#L652-L658

### PR DESCRIPTION
**Pull request by dyceron**
Not ideal as it doesn't truly fix the issue, but it prevents the memory errors (and a crash on console). A proper fix in the future would be better.
Fixes #209 temporarily

https://github.com/randovania/open-samus-returns-rando/assets/38679103/2780fd7d-6141-4c90-bf4c-6a7b3437fc6e

### CODE REVIEW

File: src/open_samus_returns_rando/files/levels/s040_area4.lua [hunk 1]
```diff
@@ -207,16 +207,21 @@ function s040_area4.OnEnter_Gamma_001_Dead()
     Game.SetSubAreaCurrentSetup("collision_camera_012", "PostGamma_001", true)
     Game.SetSubAreaCurrentSetup("collision_camera_013", "PostGamma_001", true)
     -- if Game.GetEntity("SpawnGroup019") ~= nil then
-      -- Game.GetEntity("SpawnGroup019").SPAWNGROUP:EnableSpawnGroup()
+    --   Game.GetEntity("SpawnGroup019").SPAWNGROUP:EnableSpawnGroup()
```
Comment (ThanatosGit) [inline src/open_samus_returns_rando/files/levels/s040_area4.lua:210]: The whole thing can be reverted as we need to reload the whole room anyways. 
Here and in the `OnSubAreaChange`.

**Review by ThanatosGit — APPROVED** [review]

**Comment by dyceron** [comment]
In the future, we can figure out how to properly fix this or improve how this workaround is done.
